spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 9e549de167fb0f65a9de
            clientSecret: 699720000e5dc8a4338f242844a6f92e66b1b438
            redirect-uri: "{baseUrl}/auth/oauth2/github/code/{registrationId}"
            scope:
              - user:email
              - read:user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/news_portal?characterEncoding=utf-8&userSSL=false
    username: root
    password: 85801754yY!
    type: com.zaxxer.hikari.HikariDataSource


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.github.news_portal.domain